// generated by @2qp0 and @credential_
// roblox version: 0.718.601.39366
// roblox hash: version-acc4b74f79e743b9
// join my executor server: discord.gg/HTG8P6hHSW

#pragma once
#include <cstdint>

namespace offsets {
    namespace Instance {
        constexpr std::uintptr_t new = 0x106A9D0;
    }

    namespace Raknet {
        constexpr std::uintptr_t HandleConnectionState = 0xA8DC10;
    }

    namespace core {
        constexpr std::uintptr_t Bridge_registerClass = 0x1C74260;
        constexpr std::uintptr_t KTable = 0x7561830;
        constexpr std::uintptr_t LuaVMLoad = 0x33BA660;
        constexpr std::uintptr_t PhysicalPropertiesBridge_registerClass = 0x47829B0;
        constexpr std::uintptr_t close = 0x44097E0;
        constexpr std::uintptr_t close_state = 0x43CEBA0;
        constexpr std::uintptr_t compress = 0x464D870;
        constexpr std::uintptr_t create = 0x44090B0;
        constexpr std::uintptr_t currfuncname = 0x43D0240;
        constexpr std::uintptr_t f_luaopen = 0x43CDE40;
        constexpr std::uintptr_t freeblock = 0x4423270;
        constexpr std::uintptr_t freeclasspage = 0x44230A0;
        constexpr std::uintptr_t functionContainer = 0x1CB59E0;
        constexpr std::uintptr_t get_capabilites = 0x44CEFE0;
        constexpr std::uintptr_t isyieldable = 0x44097B0;
        constexpr std::uintptr_t loadLibraryProtected = 0x1D809D0;
        constexpr std::uintptr_t luaA_toobject = 0x43C8F10;
        constexpr std::uintptr_t luaC_step = 0x43DAE30;
        constexpr std::uintptr_t luaD_rawrunprotected = 0x43CB020;
        constexpr std::uintptr_t luaD_throw = 0x43CB050;
        constexpr std::uintptr_t luaF_newproto = 0x44325B0;
        constexpr std::uintptr_t luaG_runerrorL = 0x43DBEC0;
        constexpr std::uintptr_t luaL_argerrorL = 0x43D02C0;
        constexpr std::uintptr_t luaL_checkany = 0x4404C10;
        constexpr std::uintptr_t luaL_checklstring = 0x43D2130;
        constexpr std::uintptr_t luaL_errorL = 0x48E2650;
        constexpr std::uintptr_t luaL_findtable = 0x43D47D0;
        constexpr std::uintptr_t luaL_newmetatable = 0x48A6D00;
        constexpr std::uintptr_t luaL_pushresult = 0x43D6BA0;
        constexpr std::uintptr_t luaL_register = 0x2BD9390;
        constexpr std::uintptr_t luaL_typeerrorL = 0x43D0340;
        constexpr std::uintptr_t luaM_free = 0x4423330;
        constexpr std::uintptr_t luaM_freegco = 0x44233B0;
        constexpr std::uintptr_t luaM_toobig = 0x4422F50;
        constexpr std::uintptr_t luaM_visitgco = 0x44234C0;
        constexpr std::uintptr_t luaO_chunkid = 0x443A020;
        constexpr std::uintptr_t luaO_pushfstring = 0x4439FF0;
        constexpr std::uintptr_t luaT_objtypename = 0x4432590;
        constexpr std::uintptr_t luaV_getimport = 0x45B9F30;
        constexpr std::uintptr_t luaV_settable = 0x15AB160;
        constexpr std::uintptr_t lua_pushfstringL = 0x43C9FA0;
        constexpr std::uintptr_t lua_pushvfstring = 0x43C9F30;
        constexpr std::uintptr_t lua_rawcheckstack = 0x43C9360;
        constexpr std::uintptr_t lua_xmove = 0x43C9680;
        constexpr std::uintptr_t luau_execute = 0x43E4590;
        constexpr std::uintptr_t luau_load = 0x228ED15;
        constexpr std::uintptr_t newblock = 0x44231E0;
        constexpr std::uintptr_t newclasspage = 0x4423030;
        constexpr std::uintptr_t newgcoblock = 0x4423140;
        constexpr std::uintptr_t newpage = 0x4422F80;
        constexpr std::uintptr_t newproxy = 0x4405F40;
        constexpr std::uintptr_t openState = 0xBC4B50;
        constexpr std::uintptr_t pseudo2addr = 0x43C8E50;
        constexpr std::uintptr_t pushInstance = 0x1D77540;
        constexpr std::uintptr_t remapUserdataTypes = 0x43DCD70;
        constexpr std::uintptr_t resume = 0xE442C0;
        constexpr std::uintptr_t running = 0x4409750;
        constexpr std::uintptr_t status = 0x4407CD0;
        constexpr std::uintptr_t std_runtime_error = 0x47C0E50;
        constexpr std::uintptr_t wrap = 0x4409560;
        constexpr std::uintptr_t yield = 0x44096F0;
    }

    namespace task {
        constexpr std::uintptr_t cancel = 0x1E31A80;
        constexpr std::uintptr_t defer = 0x152B100;
        constexpr std::uintptr_t wait = 0x3D99860;  // candidates: 0x3D99860
    }

} // .gg/zzzzhub
