// version hash: version-acc4b74f79e743b9
// join my executor server: discord.gg/HTG8P6hHSW
// generated by @2qp0 and @credential_ optimized by @arsongoon
// roblox version: 0.719.0.47915 (before this wasnt accurate apologies kings and queens)
// brutual offset mog
#pragma once
#include <cstdint>

namespace offsets {
    namespace Instance {
        constexpr std::uintptr_t fromExisting = 0x1055530;  // candidates: 0x1055530
        constexpr std::uintptr_t new = 0x104F560;
    }

    namespace OpCode {
        constexpr std::uintptr_t Op_0 = 0xFB34DE;
        constexpr std::uintptr_t Op_1 = 0xFB34E6;
        constexpr std::uintptr_t Op_10 = 0xFB352E;
        constexpr std::uintptr_t Op_11 = 0xFB3536;
        constexpr std::uintptr_t Op_12 = 0xFB353E;
        constexpr std::uintptr_t Op_13 = 0xFB3546;
        constexpr std::uintptr_t Op_14 = 0xFB354E;
        constexpr std::uintptr_t Op_15 = 0xFB3556;
        constexpr std::uintptr_t Op_16 = 0xFB355E;
        constexpr std::uintptr_t Op_17 = 0xFB3566;
        constexpr std::uintptr_t Op_18 = 0xFB356E;
        constexpr std::uintptr_t Op_19 = 0xFB3576;
        constexpr std::uintptr_t Op_2 = 0xFB34EE;
        constexpr std::uintptr_t Op_20 = 0xFB357E;
        constexpr std::uintptr_t Op_21 = 0xFB3586;
        constexpr std::uintptr_t Op_22 = 0xFB358E;
        constexpr std::uintptr_t Op_23 = 0xFB3596;
        constexpr std::uintptr_t Op_24 = 0xFB359E;
        constexpr std::uintptr_t Op_25 = 0xFB35A6;
        constexpr std::uintptr_t Op_26 = 0xFB35AE;
        constexpr std::uintptr_t Op_27 = 0xFB35B6;
        constexpr std::uintptr_t Op_28 = 0xFB35BE;
        constexpr std::uintptr_t Op_29 = 0xFB35C6;
        constexpr std::uintptr_t Op_3 = 0xFB34F6;
        constexpr std::uintptr_t Op_30 = 0xFB35CE;
        constexpr std::uintptr_t Op_31 = 0xFB35D6;
        constexpr std::uintptr_t Op_32 = 0xFB35DE;
        constexpr std::uintptr_t Op_33 = 0xFB35E6;
        constexpr std::uintptr_t Op_34 = 0xFB35EE;
        constexpr std::uintptr_t Op_35 = 0xFB35F6;
        constexpr std::uintptr_t Op_36 = 0xFB35FE;
        constexpr std::uintptr_t Op_37 = 0xFB3606;
        constexpr std::uintptr_t Op_38 = 0xFB360E;
        constexpr std::uintptr_t Op_39 = 0xFB3616;
        constexpr std::uintptr_t Op_4 = 0xFB34FE;
        constexpr std::uintptr_t Op_40 = 0xFB361E;
        constexpr std::uintptr_t Op_41 = 0xFB3626;
        constexpr std::uintptr_t Op_42 = 0xFB362E;
        constexpr std::uintptr_t Op_43 = 0xFB3636;
        constexpr std::uintptr_t Op_44 = 0xFB363E;
        constexpr std::uintptr_t Op_45 = 0xFB3646;
        constexpr std::uintptr_t Op_46 = 0xFB364E;
        constexpr std::uintptr_t Op_47 = 0xFB3656;
        constexpr std::uintptr_t Op_48 = 0xFB365E;
        constexpr std::uintptr_t Op_49 = 0xFB3666;
        constexpr std::uintptr_t Op_5 = 0xFB3506;
        constexpr std::uintptr_t Op_50 = 0xFB366E;
        constexpr std::uintptr_t Op_51 = 0xFB3676;
        constexpr std::uintptr_t Op_52 = 0xFB367E;
        constexpr std::uintptr_t Op_53 = 0xFB3686;
        constexpr std::uintptr_t Op_54 = 0xFB368E;
        constexpr std::uintptr_t Op_55 = 0xFB3696;
        constexpr std::uintptr_t Op_56 = 0xFB369E;
        constexpr std::uintptr_t Op_57 = 0xFB36A6;
        constexpr std::uintptr_t Op_58 = 0xFB36AE;
        constexpr std::uintptr_t Op_59 = 0xFB36B6;
        constexpr std::uintptr_t Op_6 = 0xFB350E;
        constexpr std::uintptr_t Op_60 = 0xFB36BE;
        constexpr std::uintptr_t Op_61 = 0xFB36C6;
        constexpr std::uintptr_t Op_62 = 0xFB36CE;
        constexpr std::uintptr_t Op_63 = 0xFB36D6;
        constexpr std::uintptr_t Op_64 = 0xFB36DE;
        constexpr std::uintptr_t Op_65 = 0xFB36E6;
        constexpr std::uintptr_t Op_66 = 0xFB36EE;
        constexpr std::uintptr_t Op_67 = 0xFB36F6;
        constexpr std::uintptr_t Op_68 = 0xFB36FE;
        constexpr std::uintptr_t Op_69 = 0xFB3706;
        constexpr std::uintptr_t Op_7 = 0xFB3516;
        constexpr std::uintptr_t Op_70 = 0xFB370E;
        constexpr std::uintptr_t Op_71 = 0xFB3716;
        constexpr std::uintptr_t Op_72 = 0xFB371E;
        constexpr std::uintptr_t Op_73 = 0xFB3726;
        constexpr std::uintptr_t Op_74 = 0xFB372E;
        constexpr std::uintptr_t Op_75 = 0xFB3736;
        constexpr std::uintptr_t Op_76 = 0xFB373E;
        constexpr std::uintptr_t Op_77 = 0xFB3746;
        constexpr std::uintptr_t Op_78 = 0xFB374E;
        constexpr std::uintptr_t Op_79 = 0xFB3756;
        constexpr std::uintptr_t Op_8 = 0xFB351E;
        constexpr std::uintptr_t Op_80 = 0xFB375E;
        constexpr std::uintptr_t Op_81 = 0xFB3766;
        constexpr std::uintptr_t Op_82 = 0xFB376E;
        constexpr std::uintptr_t Op_83 = 0xFB3776;
        constexpr std::uintptr_t Op_84 = 0xFB377E;
        constexpr std::uintptr_t Op_85 = 0xFB3786;
        constexpr std::uintptr_t Op_86 = 0xFB378E;
        constexpr std::uintptr_t Op_87 = 0xFB3796;
        constexpr std::uintptr_t Op_88 = 0xFB379E;
        constexpr std::uintptr_t Op_89 = 0xFB37A6;
        constexpr std::uintptr_t Op_9 = 0xFB3526;
        constexpr std::uintptr_t Op_90 = 0xFB37AE;
        constexpr std::uintptr_t Op_91 = 0xFB37B6;
        constexpr std::uintptr_t Op_92 = 0xFB37BE;
        constexpr std::uintptr_t Op_93 = 0xFB37C6;
        constexpr std::uintptr_t Op_94 = 0xFB37CE;
        constexpr std::uintptr_t Op_95 = 0xFB37D6;
        constexpr std::uintptr_t Op_96 = 0xFB37DE;
        constexpr std::uintptr_t Op_97 = 0xFB37E6;
        constexpr std::uintptr_t Op_98 = 0xFB37EE;
        constexpr std::uintptr_t Op_99 = 0xFB37F6;
    }

    namespace RBX {
        constexpr std::uintptr_t StandardOut_print = 0x1E21AD0;
    }

    namespace Raknet {
        constexpr std::uintptr_t HandleConnectionState = 0xA51C90;  // candidates: 0xA51C90
        constexpr std::uintptr_t ProcessNetworkPacket = 0x134A800;
        constexpr std::uintptr_t ReportNetworkError = 0xA4FA10;
    }

    namespace ScriptContext {
        constexpr std::uintptr_t resume = 0x1D7CD20;
    }

    namespace core {
        constexpr std::uintptr_t Bridge_registerClass = 0x1C3F4E0;
        constexpr std::uintptr_t FireProximityPrompt = 0x2686F80;  // candidates: 0x2686F80
        constexpr std::uintptr_t FireTouchInterest = 0x2A360C0;
        constexpr std::uintptr_t GetLuaState = 0x1C4BAD0;
        constexpr std::uintptr_t GetProperty = 0x4788A30;
        constexpr std::uintptr_t IdentityPtr = 0x7661528;
        constexpr std::uintptr_t KTable = 0x751A7B0;  // candidates: 0x751A7B0
        constexpr std::uintptr_t KTable_Alt = 0x751A7B0;
        constexpr std::uintptr_t LuaVMLoad = 0x1C81E80;
        constexpr std::uintptr_t Lua_protect_metatable = 0x1D47100;  // candidates: 0x1D47100
        constexpr std::uintptr_t OpCode = 0x646C630;
        constexpr std::uintptr_t PhysicalPropertiesBridge_registerClass = 0x1CE1400;
        constexpr std::uintptr_t RawScheduler = 0x7CF5400;
        constexpr std::uintptr_t RequestCode = 0x1C4BED0;
        constexpr std::uintptr_t RobloxLogCrash = 0x4788A30;
        constexpr std::uintptr_t SandBoxThread = 0x1730220;
        constexpr std::uintptr_t Vector2Bridge_registerClass = 0x1D11D20;
        constexpr std::uintptr_t Vector3Bridge_registerClass = 0x1D0F500;
        constexpr std::uintptr_t auxgetinfo = 0x43A7890;
        constexpr std::uintptr_t auxopen = 0x43CDC30;
        constexpr std::uintptr_t close = 0x43D1160;
        constexpr std::uintptr_t close_state = 0x43973A0;
        constexpr std::uintptr_t compress = 0x1C80D50;
        constexpr std::uintptr_t create = 0x43D0A20;
        constexpr std::uintptr_t currfuncname = 0x4398990;
        constexpr std::uintptr_t error_code_check = 0x43B2F50;
        constexpr std::uintptr_t f_luaopen = 0x43A8530;
        constexpr std::uintptr_t freeblock = 0x43EF460;
        constexpr std::uintptr_t freeclasspage = 0x43EF280;
        constexpr std::uintptr_t functionContainer = 0x1C80C00;
        constexpr std::uintptr_t getTaskScheduler = 0x1384E80;
        constexpr std::uintptr_t get_capabilites = 0x4498760;
        constexpr std::uintptr_t info = 0x43C17D0;  // candidates: 0x45E9A00
        constexpr std::uintptr_t isyieldable = 0x43D1130;
        constexpr std::uintptr_t loadLibraryProtected = 0x1D4C2E0;
        constexpr std::uintptr_t loadsafe = 0x43A8540;
        constexpr std::uintptr_t luaA_toobject = 0x43911C0;
        constexpr std::uintptr_t luaB_xpcallcont = 0x43CF300;
        constexpr std::uintptr_t luaC_step = 0x43A36C0;
        constexpr std::uintptr_t luaD_rawrunprotected = 0x4393810;
        constexpr std::uintptr_t luaD_throw = 0x4393840;
        constexpr std::uintptr_t luaF_freeproto = 0x43FE820;
        constexpr std::uintptr_t luaF_newproto = 0x43FE8C0;
        constexpr std::uintptr_t luaG_runerrorL = 0x43A4740;
        constexpr std::uintptr_t luaH_dummynode = 0x5F518C8;
        constexpr std::uintptr_t luaL_argerrorL = 0x4398A10;
        constexpr std::uintptr_t luaL_checkany = 0x43CC580;
        constexpr std::uintptr_t luaL_checklstring = 0x439A830;
        constexpr std::uintptr_t luaL_checktype = 0x4398B80;
        constexpr std::uintptr_t luaL_errorL = 0x48A9500;
        constexpr std::uintptr_t luaL_findtable = 0x48D14E0;
        constexpr std::uintptr_t luaL_getmetafield = 0x439A8E0;
        constexpr std::uintptr_t luaL_newmetatable = 0x486DB50;
        constexpr std::uintptr_t luaL_pushresult = 0x439F3B0;
        constexpr std::uintptr_t luaL_register = 0x2BBD720;
        constexpr std::uintptr_t luaL_typeerrorL = 0x439C2D0;
        constexpr std::uintptr_t luaL_where = 0x4398BB0;
        constexpr std::uintptr_t luaM_free = 0x43EF520;
        constexpr std::uintptr_t luaM_freegco = 0x43EF5A0;
        constexpr std::uintptr_t luaM_toobig = 0x43EF130;
        constexpr std::uintptr_t luaM_visitgco = 0x43EF6C0;
        constexpr std::uintptr_t luaO_chunkid = 0x44063A0;
        constexpr std::uintptr_t luaO_nilobject = 0x5F52318;
        constexpr std::uintptr_t luaO_pushfstring = 0x4406370;
        constexpr std::uintptr_t luaO_pushvfstring = 0x4405C70;
        constexpr std::uintptr_t luaT_objtypename = 0x43FE8A0;
        constexpr std::uintptr_t luaT_objtypenamestr = 0x43FE710;
        constexpr std::uintptr_t luaV_getimport = 0x43A4F40;
        constexpr std::uintptr_t luaV_gettable = 0x43A4E90;
        constexpr std::uintptr_t luaV_settable = 0x43A50D0;
        constexpr std::uintptr_t lua_newstate = 0x10155E0;
        constexpr std::uintptr_t lua_pcall = 0x4393920;
        constexpr std::uintptr_t lua_pushfstringL = 0x43921D0;
        constexpr std::uintptr_t lua_pushvfstring = 0x4392160;
        constexpr std::uintptr_t lua_rawcheckstack = 0x4391620;
        constexpr std::uintptr_t lua_xmove = 0x4391940;
        constexpr std::uintptr_t luaopen_base = 0x43CE300;
        constexpr std::uintptr_t luau_execute = 0x43AD490;
        constexpr std::uintptr_t luau_load = 0x4395020;
        constexpr std::uintptr_t newblock = 0x43EF310;
        constexpr std::uintptr_t newclasspage = 0x43EF210;
        constexpr std::uintptr_t newgcoblock = 0x43EF3C0;
        constexpr std::uintptr_t newpage = 0x43EF160;
        constexpr std::uintptr_t newproxy = 0x43CD8C0;
        constexpr std::uintptr_t openState = 0x1D4C590;
        constexpr std::uintptr_t print = 0x1E21AD0;
        constexpr std::uintptr_t pseudo2addr = 0x4391100;
        constexpr std::uintptr_t pushInstance = 0x1D43290;
        constexpr std::uintptr_t readVarInt = 0xA1E7D0;
        constexpr std::uintptr_t remapUserdataTypes = 0x43A55D0;
        constexpr std::uintptr_t resume = 0x1D7CD20;
        constexpr std::uintptr_t running = 0x43D10D0;
        constexpr std::uintptr_t startScript = 0x45219C0;
        constexpr std::uintptr_t status = 0x43CF640;
        constexpr std::uintptr_t std_runtime_error = 0x4787900;
        constexpr std::uintptr_t tostring = 0x43A75F0;
        constexpr std::uintptr_t traceback = 0x43A7A90;
        constexpr std::uintptr_t wrap = 0x43D0EE0;
        constexpr std::uintptr_t yield = 0x43D1070;
    }

    namespace task {
        constexpr std::uintptr_t cancel = 0x486B610;
        constexpr std::uintptr_t defer = 0x486B720;
        constexpr std::uintptr_t delay = 0x256D6A0;
        constexpr std::uintptr_t desynchronize = 0x486B8F0;
        constexpr std::uintptr_t spawn = 0x486BC10;
        constexpr std::uintptr_t synchronize = 0x486B820;
        constexpr std::uintptr_t wait = 0x3D68470;
    }

    namespace xref {
        constexpr std::uintptr_t ROBLOX_singletonEvent = 0x71BC7A;
    }

} // .gg/zzzzhub
