// offset format example <3
// made by zzzz

namespace Offsets {
    const uintptr_t BinableEventEventSink =
    const uintptr_t BinableEventListenerList = 
    const uintptr_t BinableEventListenerListRef = 
    const uintptr_t BinableEventMaskBits = 
    const uintptr_t BinableEventSecurityCaps = 
    const uintptr_t BinableEventSignals = 
    const uintptr_t BinableFunctionSignalHead = 
    const uintptr_t BindableFunctionSignalNet = 
    const uintptr_t BindableFunctionSignalPrev = 
    const uintptr_t BindableFunctionSignalAux = 
    const uintptr_t BindableFunctionSignalAux = 
    const uintptr_t BindableFunctionSignalSentinel = 
    const uintptr_t BindableFunctionInvokeCallback = 
    const uintptr_t BindableFunctionSecurityCaps = 
    const uintptr_t Children = 
    const uintptr_t ClassDescriptor = 
    const uintptr_t ClassName = 
    const uintptr_t DescriptorName = 
    const uintptr_t FakeDataModelToReal = 
    const uintptr_t JobName = 
    const uintptr_t JobsEnd = 
    const uintptr_t JobsStart =  
    const uintptr_t LocalScriptBytecode = 
    const uintptr_t ModuleScriptBytecode = 
    const uintptr_t Name = 
    const uintptr_t Overlap = 
    const uintptr_t Parent = 
    const uintptr_t Primitive = 
    const uintptr_t BasePartToPrimitivePointer = 
    const uintptr_t PropertyBucketIndices = 
    const uintptr_t PropDescriptor = 
    const uintptr_t PropertyDescriptors = 
    const uintptr_t PropertyDescriptorBitFlags = 
    const uintptr_t PropertyHashTable = 
    const uintptr_t PropertyIndeMask = 
    const uintptr_t RakPeer = 
    const uintptr_t RenderJobToView = 
    const uintptr_t RenderViewToDevice = 
    const uintptr_t RequireFlag = 
    const uintptr_t DataModelScriptContet = 
    const uintptr_t ScriptContet = 
    const uintptr_t Scriptable = 
    const uintptr_t ScriptableFlags = 
    const uintptr_t TaskSchedulerMaFps = 
    const uintptr_t TStringNet = 
    const uintptr_t TStringHash = 
    const uintptr_t TStringLen = 
    const uintptr_t LuaTableMetatable = 
    const uintptr_t LuaTableArray = 
    const uintptr_t LuaTableNode = 
    const uintptr_t LuaTableGcList = 
    const uintptr_t LuaPagePrev =
    const uintptr_t LuaPageNet = 
    const uintptr_t LuaPageListPrev = 
    const uintptr_t LuaPageListNet = 
    const uintptr_t LuaPagePageSize = 
    const uintptr_t LuaPageBlockSize =
    const uintptr_t LuaPageFreeList = 
    const uintptr_t LuaPageFreeNet =
    const uintptr_t LuaPageBusyBlocks = 
    const uintptr_t LuaPageData = 
    const uintptr_t LuaStateGlobal = 
    const uintptr_t LuaStateStackLast = 
    const uintptr_t LuaStateTop = 
    const uintptr_t LuaStateNameCall = 
    const uintptr_t LuaStateCi = 
    const uintptr_t LuaStateBase = 
    const uintptr_t LuaStateStack = 
    const uintptr_t LuaStateRobloEtraSpace =
    const uintptr_t LuaStateEndCi = 
    const uintptr_t LuaStateBaseCi = 
    const uintptr_t LuaStateNCCalls = 
    const uintptr_t LuaStateBaseCCalls = 
    const uintptr_t LuaStateCachedSlot = 
    const uintptr_t LuaStateGt = 
    const uintptr_t LuaStateOpenUpval = 
    const uintptr_t LuaStateUserData =
    const uintptr_t GlobalCallbacks = 
    const uintptr_t GlobalCbGcStep = 
    const uintptr_t GlobalCbOnAllocate =
    const uintptr_t GlobalCbUserThread =
    const uintptr_t GlobalCbClose = 
    const uintptr_t GlobalFreePages = 
    const uintptr_t GlobalFreeGcoPages = 
    const uintptr_t GlobalUdataMt = 
    const uintptr_t VisualEngineToDevice =
}

namespace Signal {
    namespace BindableEvent {
        const uintptr_t EventSink = Offsets::BindableEventEventSink
        const uintptr_t ListenerList = Offsets::BindableEventListenerList
        const uintptr_t ListenerListRef = Offsets::BindableEventListenerListRef
        const uintptr_t MaskBits = Offsets::BindableEventMaskBits
        const uintptr_t SecurityCaps = Offsets::BindableEventSecurityCaps
        const uintptr_t Signals = Offsets::BindableEventSignals
    }

    namespace BindableFunction {
        const uintptr_t SignalHead = Offsets::BindableFunctionSignalHead
        const uintptr_t SignalNet = Offsets::BindableFunctionSignalNet
        const uintptr_t SignalPrev = Offsets::BindableFunctionSignalPrev
        const uintptr_t SignalAu- = Offsets::BindableFunctionSignalAu-
        const uintptr_t SignalAu = Offsets::BindableFunctionSignalAu
        const uintptr_t SignalSentinel = Offsets::BindableFunctionSignalSentinel
        const uintptr_t InvokeCallback = Offsets::BindableFunctionInvokeCallback
        const uintptr_t SecurityCaps = Offsets::BindableFunctionSecurityCaps
    }
}

namespace Structs {
    const uintptr_t AppDataInfo = 
    const uintptr_t FakeDataModel = 
    const uintptr_t IdentityPtr =
    const uintptr_t LuauOpcode = 
    const uintptr_t KTable = 
    const uintptr_t RawSchedulerHumanoidParallelManagerCtor = 
    const uintptr_t luaO_nilobject = 
    const uintptr_t luaH_dummynode = 
    const uintptr_t luaT_typenames = 
    const uintptr_t luaT_eventnames = 
    const uintptr_t TaskSchedulerPointer = 
    const uintptr_t VisualEnginePointer = 
    const uintptr_t PlayerConfigurerPointer = 
}

namespace Functions {
    const uintptr_t AttachRobloxExtraSpace = 
    const uintptr_t print = 
    const uintptr_t getluastate = 
    const uintptr_t getglobalstate =
    const uintptr_t luavm__load = 
    const uintptr_t loadsafe = 
    const uintptr_t luaD_throw = 
    const uintptr_t luaD_rawrunprotected = 
    const uintptr_t luaG_runerrorL = 
    const uintptr_t callerrfunc = 
    const uintptr_t close_state = 
    const uintptr_t f_luaopen = 
    const uintptr_t luau_execute = 
    const uintptr_t luaC_step = 
    const uintptr_t freegco = 
    const uintptr_t markroot = 
    const uintptr_t propagatemark = 
    const uintptr_t atomic = 
    const uintptr_t traversetable = 
    const uintptr_t luaM_free_ = 
    const uintptr_t luaM_freegco_ = 
    const uintptr_t luaM_visitgco = 
    const uintptr_t newblock = 
    const uintptr_t newgcoblock = 
    const uintptr_t newpage = 
    const uintptr_t luaL_register = 
    const uintptr_t luaL_findtable = 
    const uintptr_t luaL_getmetafield = 
    const uintptr_t luaL_callmeta = 
    const uintptr_t luaL_checklstring = 
    const uintptr_t luaL_argerrorL = 
    const uintptr_t luaL_errorL = 
    const uintptr_t luaL_typerrorL = 

    const uintptr_t currfuncname = 
    const uintptr_t currentline = 

    const uintptr_t lua_typename = 
    const uintptr_t luaA_toobject = 
    const uintptr_t pseudoaddr = 
    const uintptr_t pusherror = 
    const uintptr_t tag_error = 
    const uintptr_t luaL_tolstring = 
    const uintptr_t luaL_where = 
    const uintptr_t luaT_objtypename = 
    const uintptr_t luaH_new = 
    const uintptr_t luaH_clone = 
    const uintptr_t luaO_pushfstring = 
    const uintptr_t lua_pushfstringL = 
    const uintptr_t lua_pushvfstring = 
    const uintptr_t luaO_pushvfstring = 
    const uintptr_t luaO_chunkid = 
    const uintptr_t luaV_gettable = 
    const uintptr_t luaF_newproto = 
    const uintptr_t luaF_newLclosure = 
    const uintptr_t luaF_freeproto = 
    const uintptr_t luaopen_base = 
    const uintptr_t luaopen_math = 

    const uintptr_t task_cancel = 
    const uintptr_t task_defer = 
    const uintptr_t task_delay = 
    const uintptr_t task_desynchronize = 
    const uintptr_t task_synchronize = 
    const uintptr_t task_spawn = 
    const uintptr_t task_wait = 

    const uintptr_t luaB_assert = 
    const uintptr_t luaB_error = 
    const uintptr_t luaB_gcinfo = 
    const uintptr_t luaB_getfenv = 
    const uintptr_t luaB_getmetatable = 
    const uintptr_t luaB_net = 
    const uintptr_t luaB_newproy = 
    const uintptr_t luaB_pcallrun = 
    const uintptr_t luaB_pcally =
    const uintptr_t luaB_pcally = 
    const uintptr_t luaB_print = 
    const uintptr_t luaB_rawequal = 
    const uintptr_t luaB_rawget = 
    const uintptr_t luaB_rawset =
    const uintptr_t luaB_rawlen = 
    const uintptr_t luaB_select = 
    const uintptr_t luaB_setfenv = 
    const uintptr_t luaB_setmetatable = 
    const uintptr_t luaB_tonumber = 
    const uintptr_t luaB_tostring =
    const uintptr_t luaB_type =
    const uintptr_t luaB_typeof =
    const uintptr_t umpobj =
    const uintptr_t umpthread =
    const uintptr_t enumobj =
    const uintptr_t enumtable =
    const uintptr_t interruptThread =
    const uintptr_t FireLeftMouseClick =
    const uintptr_t FireMouseHoverEnter =
    const uintptr_t FireMouseHoverLeave =
    const uintptr_t FireRightMouseClick =
    const uintptr_t FireProimityPrompt =
    const uintptr_t GetAppataInfo =
    const uintptr_t GetCapabilities =
    const uintptr_t IentityToCaps =
    const uintptr_t GetIdentityStruct =
    const uintptr_t GetValues =
    const uintptr_t GetCurrentThreaI =
    const uintptr_t NewInstance =
    const uintptr_t ProcessNetworkPacket =
    const uintptr_t RaknetSend =
    const uintptr_t IsLegalSendEvent =
    const uintptr_t IsCoreScript =
    const uintptr_t GameID =
    const uintptr_t GameLoaded =
    const uintptr_t PushInstance =
    const uintptr_t VariantCastInt =
    const uintptr_t lua_reallocstack =
    const uintptr_t lua_newstate =
    const uintptr_t lua_resetthread =
    const uintptr_t lua_yield =
    const uintptr_t lua_eception =
    const uintptr_t coroutine_resume =
    const uintptr_t cocreate =
    const uintptr_t coclose =
    const uintptr_t lua_clock =
    const uintptr_t luaT_init =
    const uintptr_t Connectionisconnect =
    const uintptr_t ScriptContextResume =
    const uintptr_t HashTable =
    const uintptr_t GetProperty =
    const uintptr_t FireTouchInterestOverlapGuard =
    const uintptr_t LuaTypenameFromTag =
    const uintptr_t LuaMethodispatchTableResolve =
    const uintptr_t GetFFlagIXPRowApplicator =
}
